export const UPDATE_REQUESTING = 'UPDATE_REQUESTING';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_UNSUCCESS = 'UPDATE_UNSUCCESS';
